// cloudfunctions/quickstartFunctions/autoEvaluateFinalAll/index.js
const cloud = require('wx-server-sdk')

cloud.init({
  env: cloud.DYNAMIC_CURRENT_ENV
})

const db = cloud.database()

/**
 * 一键为所有终评专家生成评分
 * 从 pottery_submissions_for_final 读取作品
 * 为每位终评专家生成评分
 */
exports.main = async (event, context) => {
  try {
    const {
      expertCount = 5,  // 模拟5位终评评委
      batchSize = 50    // 每批处理50件作品
    } = event;
    
    console.log('=== 开始一键终评评分 ===');
    console.log('模拟专家数量:', expertCount);
    
    // 1. 获取所有终评作品（分批）
    const MAX_LIMIT = 100;
    let allSubmissions = [];
    let skip = 0;
    let hasMore = true;
    
    while (hasMore) {
      const result = await db.collection('pottery_submissions_for_final')
        .where({
          qualification: db.command.neq(false)
        })
        .skip(skip)
        .limit(MAX_LIMIT)
        .get();
      
      allSubmissions = allSubmissions.concat(result.data);
      skip += MAX_LIMIT;
      hasMore = result.data.length === MAX_LIMIT;
      
      console.log(`已读取 ${allSubmissions.length} 件作品...`);
    }
    
    console.log('终评评分表作品总数:', allSubmissions.length);
    
    // 统计视频作品数量
    const videoCount = allSubmissions.filter(item => item.workType === 'video').length;
    console.log('其中视频作品:', videoCount, '件');
    
    // 统计港澳台作品数量
    const hkMacauTaiwanCount = allSubmissions.filter(item => {
      const province = item.schoolProvinces || '';
      return province === '香港' || province === '澳门' || province === '台湾' ||
             province === '香港特别行政区' || province === '澳门特别行政区' || province === '台湾省';
    }).length;
    console.log('其中港澳台作品:', hkMacauTaiwanCount, '件');
    
    if (allSubmissions.length === 0) {
      return {
        success: true,
        message: '没有需要评分的作品',
        data: { evaluatedCount: 0 }
      };
    }
    
    // 2. 生成模拟终评专家信息
    const mockExperts = [];
    for (let i = 0; i < expertCount; i++) {
      mockExperts.push({
        expertId: `mock_final_expert_${i + 1}`,
        expertCode: `MOCKF${String(i + 1).padStart(3, '0')}`,
        expertName: `模拟终评专家${i + 1}`,
        ip: `192.168.2.${i + 1}`
      });
    }
    
    console.log('生成模拟终评专家:', mockExperts.map(e => e.expertCode).join(', '));
    
    let processedCount = 0;
    
    // 3. 分批处理作品
    for (let i = 0; i < allSubmissions.length; i += batchSize) {
      const batch = allSubmissions.slice(i, i + batchSize);
      const promises = [];
      
      for (const submission of batch) {
        // 为这个作品生成所有专家的评分
        const evaluations = submission.evaluations || [];
        
        for (const expert of mockExperts) {
          // 检查该专家是否已评分
          const existingIndex = evaluations.findIndex(e => e.expertCode === expert.expertCode);
          
          if (existingIndex >= 0) {
            // 已评分，跳过
            continue;
          }
          
          // 生成随机评分
          const themeFit = getRandomScore(0, 3);       // 0-3分
          const creativity = getRandomScore(0, 3);      // 0-3分
          const craftsmanship = getRandomScore(0, 2);   // 0-2分
          const aesthetics = getRandomScore(0, 2);      // 0-2分
          
          const totalScore = themeFit + creativity + craftsmanship + aesthetics;
          
          // 随机决定是否有扣分项（5%概率）
          const hasDeduction = Math.random() < 0.05;
          const deductions = {};
          let deductionPoints = 0;
          
          if (hasDeduction) {
            if (Math.random() < 0.5) {
              deductions.aiNotLabeled = true;
              deductionPoints += 2;
            }
            if (Math.random() < 0.3) {
              deductions.missingCreativeStatement = true;
              deductionPoints += 1;
            }
          }
          
          const finalScore = Math.max(0, totalScore - deductionPoints);
          
          // 创建评分记录
          evaluations.push({
            expertId: expert.expertId,
            expertCode: expert.expertCode,
            expertName: expert.expertName,
            themeFit: themeFit,
            creativity: creativity,
            craftsmanship: craftsmanship,
            aesthetics: aesthetics,
            totalScore: totalScore,
            finalScore: finalScore,
            deductions: deductions,
            evaluationTime: new Date(Date.now() - Math.random() * 86400000), // 随机时间（1天内）
            ip: expert.ip,
            _isAutoGenerated: true  // 标记为自动生成
          });
        }
        
        // 更新作品的 evaluations 字段（写入终评评分表）
        promises.push(
          db.collection('pottery_submissions_for_final')
            .doc(submission._id)
            .update({
              data: {
                evaluations: evaluations
              }
            })
        );
      }
      
      // 执行批量更新
      await Promise.all(promises);
      processedCount += batch.length;
      console.log(`已处理 ${processedCount}/${allSubmissions.length} 件作品`);
    }
    
    console.log('');
    console.log('=== ✅ 一键终评评分完成 ===');
    console.log('处理作品数:', allSubmissions.length);
    console.log('包含视频作品:', videoCount, '件');
    console.log('包含港澳台作品:', hkMacauTaiwanCount, '件');
    console.log('');
    
    return {
      success: true,
      message: `已成功为 ${allSubmissions.length} 件作品生成终评评分（含${videoCount}件视频，${hkMacauTaiwanCount}件港澳台）`,
      data: {
        evaluatedCount: allSubmissions.length,
        expertsCount: expertCount,
        totalEvaluations: allSubmissions.length * expertCount,
        videoCount: videoCount,
        hkMacauTaiwanCount: hkMacauTaiwanCount
      }
    };
    
  } catch (error) {
    console.error('一键终评评分失败:', error);
    return {
      success: false,
      message: '一键终评评分失败',
      error: error.message
    };
  }
}

/**
 * 生成随机评分（偏向高分）
 */
function getRandomScore(min, max) {
  const weights = [];
  for (let i = min; i <= max; i++) {
    const weight = Math.pow(2, i - min);
    weights.push({ score: i, weight: weight });
  }
  
  const totalWeight = weights.reduce((sum, w) => sum + w.weight, 0);
  let random = Math.random() * totalWeight;
  
  for (const w of weights) {
    random -= w.weight;
    if (random <= 0) {
      return w.score;
    }
  }
  
  return max;
}




