// cloudfunctions/quickstartFunctions/autoEvaluateFinal/index.js
const cloud = require('wx-server-sdk')

cloud.init({
  env: cloud.DYNAMIC_CURRENT_ENV
})

const db = cloud.database()

/**
 * 终评自动评分（模拟终评评委打分）
 * 从 pottery_submissions_preliminary 读取作品
 * 写入 finalEvaluation 字段
 */
exports.main = async (event, context) => {
  try {
    const {
      count = 100,           // 要评分的作品数量
      expertCode,            // 专家代码
      expertName             // 专家姓名（可选）
    } = event;
    
    // 如果没有指定专家代码，使用默认值
    const finalExpertCode = expertCode || 'MOCK_FINAL001';
    let finalExpertName = expertName || '模拟终评专家1';
    let expertId = `mock_final_expert_${finalExpertCode}`;
    
    // 如果指定了真实的专家代码，从数据库读取专家信息
    if (expertCode && !expertCode.startsWith('MOCK')) {
      const expertResult = await db.collection('experts')
        .where({ expertCode: expertCode })
        .get();
      
      if (expertResult.data.length > 0) {
        const expert = expertResult.data[0];
        finalExpertName = expert.expertName || expertName || '终评专家';
        expertId = expert._id;
        console.log('使用真实终评专家:', finalExpertName, expertCode);
      }
    }
    
    console.log('=== 开始终评自动评分 ===');
    console.log('目标评分数量:', count);
    console.log('专家:', finalExpertName, '(', finalExpertCode, ')');
    
    // 从终评评分表读取所有作品（分批）
    const MAX_LIMIT = 100;
    let allSubmissions = [];
    let skip = 0;
    let hasMore = true;
    
    while (hasMore) {
      const result = await db.collection('pottery_submissions_for_final')
        .where({
          qualification: db.command.neq(false)
        })
        .skip(skip)
        .limit(MAX_LIMIT)
        .get();
      
      allSubmissions = allSubmissions.concat(result.data);
      skip += MAX_LIMIT;
      hasMore = result.data.length === MAX_LIMIT;
      
      console.log(`已读取 ${allSubmissions.length} 件作品...`);
    }
    
    console.log('终评评分表作品总数:', allSubmissions.length);
    
    // 统计视频作品数量
    const videoCount = allSubmissions.filter(item => item.workType === 'video').length;
    console.log('其中视频作品:', videoCount, '件');
    
    // 过滤出未打分的作品（检查 evaluations 字段）
    const unevaluatedSubmissions = allSubmissions.filter(item => {
      const evals = item.evaluations || [];
      // 检查是否已有该专家的评分
      return !evals.some(eval => eval.expertCode === finalExpertCode);
    });
    
    console.log('未终评打分的作品总数:', unevaluatedSubmissions.length);
    
    // 统计未评分的视频作品数量
    const unevaluatedVideoCount = unevaluatedSubmissions.filter(item => item.workType === 'video').length;
    console.log('其中未评分的视频作品:', unevaluatedVideoCount, '件');
    
    if (unevaluatedSubmissions.length === 0) {
      return {
        success: true,
        message: '所有作品都已完成终评评分',
        data: { evaluatedCount: 0 }
      };
    }
    
    // 取前N件未打分的作品
    const toEvaluate = unevaluatedSubmissions.slice(0, count);
    console.log('将评分的作品数:', toEvaluate.length);
    
    let evaluatedCount = 0;
    const updateBatchSize = 20;
    let updatePromises = [];
    
    // 逐个作品评分
    for (const submission of toEvaluate) {
      // 生成随机评分
      const themeFit = getRandomScore(0, 3);
      const creativity = getRandomScore(0, 3);
      const craftsmanship = getRandomScore(0, 2);
      const aesthetics = getRandomScore(0, 2);
      
      const totalScore = themeFit + creativity + craftsmanship + aesthetics;
      
      // 随机决定是否有扣分项（5%概率）
      const hasDeduction = Math.random() < 0.05;
      const deductions = {};
      let deductionPoints = 0;
      
      if (hasDeduction) {
        if (Math.random() < 0.5) {
          deductions.aiNotLabeled = true;
          deductionPoints += 2;
        }
        if (Math.random() < 0.3) {
          deductions.missingCreativeStatement = true;
          deductionPoints += 1;
        }
      }
      
      const finalScore = Math.max(0, totalScore - deductionPoints);
      
      // 创建终评评分记录
      const newEvaluation = {
        expertId: expertId,
        expertCode: finalExpertCode,
        expertName: finalExpertName,
        themeFit: themeFit,
        creativity: creativity,
        craftsmanship: craftsmanship,
        aesthetics: aesthetics,
        totalScore: totalScore,
        finalScore: finalScore,
        deductions: deductions,
        evaluationTime: new Date(),
        ip: context.CLIENTIP || '192.168.1.100',
        _isAutoGenerated: true
      };
      
      // 获取现有评分
      const existingEvaluations = submission.evaluations || [];
      
      // 追加新评分
      existingEvaluations.push(newEvaluation);
      
      // 添加到批量更新队列 - 更新终评评分表
      updatePromises.push(
        db.collection('pottery_submissions_for_final')
          .doc(submission._id)
          .update({
            data: {
              evaluations: existingEvaluations
            }
          })
      );
      
      evaluatedCount++;
      
      // 每20件作品批量执行一次更新
      if (updatePromises.length >= updateBatchSize) {
        await Promise.all(updatePromises);
        updatePromises = [];
        console.log(`已终评评分 ${evaluatedCount}/${toEvaluate.length} 件作品`);
      }
    }
    
    // 处理剩余的更新
    if (updatePromises.length > 0) {
      await Promise.all(updatePromises);
      console.log(`已终评评分 ${evaluatedCount}/${toEvaluate.length} 件作品`);
    }
    
    console.log('=== 终评自动评分完成 ===');
    
    return {
      success: true,
      message: `已成功为 ${evaluatedCount} 件作品生成终评评分`,
      data: {
        evaluatedCount: evaluatedCount,
        remainingCount: unevaluatedSubmissions.length - evaluatedCount
      }
    };
    
  } catch (error) {
    console.error('终评自动评分失败:', error);
    return {
      success: false,
      message: '终评自动评分失败',
      error: error.message
    };
  }
}

/**
 * 生成随机评分（偏向高分）
 */
function getRandomScore(min, max) {
  const weights = [];
  for (let i = min; i <= max; i++) {
    const weight = Math.pow(2, i - min);
    weights.push({ score: i, weight: weight });
  }
  
  const totalWeight = weights.reduce((sum, w) => sum + w.weight, 0);
  let random = Math.random() * totalWeight;
  
  for (const w of weights) {
    random -= w.weight;
    if (random <= 0) {
      return w.score;
    }
  }
  
  return max;
}

