// cloudfunctions/quickstartFunctions/autoEvaluateInitial/index.js
const cloud = require('wx-server-sdk')

cloud.init({
  env: cloud.DYNAMIC_CURRENT_ENV
})

const db = cloud.database()

/**
 * 自动初评评分（模拟初评评委打分）
 * 为所有作品生成随机评分，加速测试
 */
exports.main = async (event, context) => {
  try {
    const {
      expertCount = 7,  // 模拟7位初评评委
      batchSize = 50    // 每批处理50件作品
    } = event;
    
    console.log('=== 开始自动初评评分 ===');
    console.log('模拟专家数量:', expertCount);
    
    // 获取所有需要初评的作品（排除视界类和港澳台）- 从清洗表读取（分批）
    const MAX_LIMIT = 100;
    let submissions = [];
    let skip = 0;
    let hasMore = true;
    
    while (hasMore) {
      const result = await db.collection('pottery_submissions_clean')
        .where({
          qualification: db.command.neq(false),
          workType: db.command.in(['regular', 'video']),  // 包含普通作品和视频作品
          category: db.command.nin(['vision', '视界', '视界类']),
          // 排除港澳台作品
          schoolProvinces: db.command.nin(['香港', '澳门', '台湾', '香港特别行政区', '澳门特别行政区', '台湾省'])
        })
        .skip(skip)
        .limit(MAX_LIMIT)
        .get();
      
      submissions = submissions.concat(result.data);
      skip += MAX_LIMIT;
      hasMore = result.data.length === MAX_LIMIT;
      
      console.log(`已读取 ${submissions.length} 件作品...`);
    }
    
    console.log('需要评分的作品数:', submissions.length);
    
    // 统计视频作品数量
    const videoCount = submissions.filter(item => item.workType === 'video').length;
    console.log('其中视频作品:', videoCount, '件');
    
    if (submissions.length === 0) {
      return {
        success: true,
        message: '没有需要评分的作品',
        data: { evaluatedCount: 0 }
      };
    }
    
    // 生成模拟专家信息
    const mockExperts = [];
    for (let i = 0; i < expertCount; i++) {
      mockExperts.push({
        expertId: `mock_expert_${i + 1}`,
        expertCode: `MOCK${String(i + 1).padStart(3, '0')}`,
        expertName: `模拟初评专家${i + 1}`,
        ip: `192.168.1.${i + 1}`
      });
    }
    
    let processedCount = 0;
    
    // 分批处理作品
    for (let i = 0; i < submissions.length; i += batchSize) {
      const batch = submissions.slice(i, i + batchSize);
      const promises = [];
      
      for (const submission of batch) {
        // 为这个作品生成所有专家的评分
        const evaluations = [];
        
        for (const expert of mockExperts) {
          // 生成随机评分
          const themeFit = getRandomScore(0, 3);       // 0-3分
          const creativity = getRandomScore(0, 3);      // 0-3分
          const craftsmanship = getRandomScore(0, 2);   // 0-2分
          const aesthetics = getRandomScore(0, 2);      // 0-2分
          
          const totalScore = themeFit + creativity + craftsmanship + aesthetics;
          
          // 随机决定是否有扣分项（5%概率）
          const hasDeduction = Math.random() < 0.05;
          const deductions = {};
          let deductionPoints = 0;
          
          if (hasDeduction) {
            // 随机选择扣分项
            if (Math.random() < 0.5) {
              deductions.aiNotLabeled = true;
              deductionPoints += 2;
            }
            if (Math.random() < 0.3) {
              deductions.missingCreativeStatement = true;
              deductionPoints += 1;
            }
          }
          
          const finalScore = Math.max(0, totalScore - deductionPoints);
          
          // 创建评分记录
          evaluations.push({
            expertId: expert.expertId,
            expertCode: expert.expertCode,
            expertName: expert.expertName,
            themeFit: themeFit,
            creativity: creativity,
            craftsmanship: craftsmanship,
            aesthetics: aesthetics,
            totalScore: totalScore,
            finalScore: finalScore,
            deductions: deductions,
            evaluationTime: new Date(Date.now() - Math.random() * 86400000), // 随机时间（1天内）
            ip: expert.ip,
            _isAutoGenerated: true  // 标记为自动生成
          });
        }
        
        // 更新作品的 evaluations 字段（写入清洗表）
        promises.push(
          db.collection('pottery_submissions_clean')
            .doc(submission._id)
            .update({
              data: {
                evaluations: evaluations
              }
            })
        );
      }
      
      // 执行批量更新
      await Promise.all(promises);
      processedCount += batch.length;
      console.log(`已处理 ${processedCount}/${submissions.length} 件作品`);
    }
    
    console.log('=== 自动初评评分完成 ===');
    
    return {
      success: true,
      message: `已成功为 ${submissions.length} 件作品生成初评评分`,
      data: {
        evaluatedCount: submissions.length,
        expertsCount: expertCount,
        totalEvaluations: submissions.length * expertCount
      }
    };
    
  } catch (error) {
    console.error('自动初评评分失败:', error);
    return {
      success: false,
      message: '自动初评评分失败',
      error: error.message
    };
  }
}

/**
 * 生成随机评分
 * @param {number} min - 最小分数
 * @param {number} max - 最大分数
 * @returns {number} - 随机分数
 */
function getRandomScore(min, max) {
  // 生成偏向高分的随机数（正态分布）
  const weights = [];
  for (let i = min; i <= max; i++) {
    // 高分权重更大
    const weight = Math.pow(2, i - min);
    weights.push({ score: i, weight: weight });
  }
  
  const totalWeight = weights.reduce((sum, w) => sum + w.weight, 0);
  let random = Math.random() * totalWeight;
  
  for (const w of weights) {
    random -= w.weight;
    if (random <= 0) {
      return w.score;
    }
  }
  
  return max; // 默认返回最高分
}






















